// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cowboy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CowboyV1Client is the client API for CowboyV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CowboyV1Client interface {
	ShootV1(ctx context.Context, in *ShootRequestV1, opts ...grpc.CallOption) (*ShootResponseV1, error)
}

type cowboyV1Client struct {
	cc grpc.ClientConnInterface
}

func NewCowboyV1Client(cc grpc.ClientConnInterface) CowboyV1Client {
	return &cowboyV1Client{cc}
}

func (c *cowboyV1Client) ShootV1(ctx context.Context, in *ShootRequestV1, opts ...grpc.CallOption) (*ShootResponseV1, error) {
	out := new(ShootResponseV1)
	err := c.cc.Invoke(ctx, "/log.CowboyV1/ShootV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CowboyV1Server is the server API for CowboyV1 service.
// All implementations must embed UnimplementedCowboyV1Server
// for forward compatibility
type CowboyV1Server interface {
	ShootV1(context.Context, *ShootRequestV1) (*ShootResponseV1, error)
	mustEmbedUnimplementedCowboyV1Server()
}

// UnimplementedCowboyV1Server must be embedded to have forward compatible implementations.
type UnimplementedCowboyV1Server struct {
}

func (UnimplementedCowboyV1Server) ShootV1(context.Context, *ShootRequestV1) (*ShootResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShootV1 not implemented")
}
func (UnimplementedCowboyV1Server) mustEmbedUnimplementedCowboyV1Server() {}

// UnsafeCowboyV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CowboyV1Server will
// result in compilation errors.
type UnsafeCowboyV1Server interface {
	mustEmbedUnimplementedCowboyV1Server()
}

func RegisterCowboyV1Server(s grpc.ServiceRegistrar, srv CowboyV1Server) {
	s.RegisterService(&CowboyV1_ServiceDesc, srv)
}

func _CowboyV1_ShootV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShootRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CowboyV1Server).ShootV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.CowboyV1/ShootV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CowboyV1Server).ShootV1(ctx, req.(*ShootRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// CowboyV1_ServiceDesc is the grpc.ServiceDesc for CowboyV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CowboyV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log.CowboyV1",
	HandlerType: (*CowboyV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShootV1",
			Handler:    _CowboyV1_ShootV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cowboy.proto",
}
